# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

run:
  timeout: 5m
  modules-download-mode: readonly

  skip-files:
    - _test.go
    - lib/bad.go

linters:
  enable:
    - errcheck
    - goimports
    - revive
    - govet
    - staticcheck
    - gocyclo
    - gosimple
    - goconst
    - misspell
    - unconvert
    - unused
    - unparam
    - govet
    - gocritic
    - prealloc
    - exportloopref
    - staticcheck
    - gosec
    - errcheck

output:
  print-issued-name: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  revive:
    rules:
      - name: package-comments
        severity: warning
        disabled: true
      - name: exported
        severity: warning
        disabled: true