name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull izacgaldino23/products-api:latest
    - name: Delete Old docker container
      run: sudo docker rm -f products-api-container-cool || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3030:3030 --name products-api-container-cool izacgaldino23/products-api